#!/bin/sh
set -eu

REPOSITORY_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
MIGRATION_DIR="$REPOSITORY_ROOT/sql/migrations"
LAST_VERSION="${1:-$(find "$MIGRATION_DIR" -maxdepth 1 -type f -name '*.sql' -exec basename {} \; | sort | tail -1 | cut -d_ -f1)}"
OUTPUT="${2:-$REPOSITORY_ROOT/sql/baselines/${LAST_VERSION}_baseline.sql}"
OUTPUT_DIR="$(dirname -- "$OUTPUT")"
TEMP_FILE="$OUTPUT.tmp.$$"

mkdir -p "$OUTPUT_DIR"
trap 'rm -f "$TEMP_FILE"' EXIT INT TERM

found=0
count=0
first_version=""
{
	printf '%s\n' '-- TMA PostgreSQL production baseline.'
	printf '%s\n' '-- Generated by scripts/generate_sql_baseline.sh; do not edit manually.'
	printf '%s\n' '-- Apply to an empty database with ON_ERROR_STOP and a single transaction.'
	printf '%s\n\n' '-- The source migrations remain authoritative for upgrades and audit history.'

	for file in "$MIGRATION_DIR"/*.sql; do
		filename="$(basename -- "$file")"
		version="${filename%%_*}"
		if [ -z "$first_version" ]; then
			first_version="$version"
		fi
		printf '\n-- -----------------------------------------------------------------------------\n'
		printf '%s\n' "-- Source migration: $filename"
		printf '%s\n\n' '-- -----------------------------------------------------------------------------'
		sed -e '$a\' "$file"
		count=$((count + 1))
		if [ "$version" = "$LAST_VERSION" ]; then
			found=1
			break
		fi
	done

	if [ "$found" -ne 1 ]; then
		printf '%s\n' "requested migration version $LAST_VERSION was not found" >&2
		exit 1
	fi
} >"$TEMP_FILE"

mv "$TEMP_FILE" "$OUTPUT"
trap - EXIT INT TERM
printf 'generated %s from %s migrations (%s through %s)\n' "$OUTPUT" "$count" "$first_version" "$LAST_VERSION"

